import assert from "node:assert/strict";
import fs from "node:fs/promises";
import test from "node:test";

test("health cards place reports with their subject and keep the iPad overview compact", async () => {
  const [main, health, mind, life, coach, styles] = await Promise.all([
    fs.readFile(new URL("../src/main.tsx", import.meta.url), "utf8"),
    fs.readFile(new URL("../src/pages/HealthPage.tsx", import.meta.url), "utf8"),
    fs.readFile(new URL("../src/pages/MindPanel.tsx", import.meta.url), "utf8"),
    fs.readFile(new URL("../src/pages/LifePanel.tsx", import.meta.url), "utf8"),
    fs.readFile(new URL("../src/pages/CoachReview.tsx", import.meta.url), "utf8"),
    fs.readFile(new URL("../src/styles.css", import.meta.url), "utf8"),
  ]);
  assert.match(health, /<MindPanel[\s\S]+?<DailyReportCard report=\{data\.reports\?\.daily/);
  assert.match(health, /<LifePanel[\s\S]+?<ReportPreview reportId="weekly"[\s\S]+?<ReportPreview reportId="monthly"/);
  assert.doesNotMatch(health, /RecentReports|health-reports-overview/);
  assert.match(health, /writeHealthView\(\{ band: id \}, "push"\)/);
  assert.match(health, /writeHealthView\(\{ report: id \}, "push"\)/);
  assert.match(health, /health-coach-review-detail/);
  assert.match(health, /aria-label=\{`打开\$\{title\}详情`\}/);
  assert.match(health, /url\.searchParams\.set\("band", band\)/);
  assert.match(health, /url\.searchParams\.set\("report", report\)/);
  assert.match(health, /<PageTrail items=\{\[\{ label: meta\.title \}\]\} \/>/);
  assert.match(health, /report\.achievements/);
  assert.match(health, /report\.interruptions/);
  assert.match(health, /report\.recovery/);
  assert.match(health, /report\.allocation/);
  assert.match(health, /report\.goodTimes/);
  assert.match(health, /report\.subjective/);
  assert.match(health, /report\.notableChange/);
  assert.match(health, /report\.oneExperiment/);
  assert.match(health, /report\.unknowns/);
  assert.match(health, /report\.sources/);
  assert.doesNotMatch(styles, /\.health-report-card\[open\]/);
  assert.match(styles, /\.health-period-reports \{[\s\S]{0,160}grid-template-columns: minmax\(0, 1fr\)/);
  assert.match(styles, /@media \(min-width: 901px\) \{[\s\S]{0,420}\.health-period-reports \{\s*grid-template-rows: repeat\(2, minmax\(0, 1fr\)\)/);
  assert.match(styles, /\.health-card-report-slot\.is-daily > \.health-report-card \{[\s\S]{0,100}flex: 1 1 auto/);
  assert.match(health, /health-report-compact-facts/);
  assert.match(health, /<CompactReportFacts report=\{report\} limit=\{3\} \/>/);
  assert.match(health, /<CompactReportFacts report=\{report\} \/>/);
  assert.match(health, /report\.achievements\.slice\(0, limit\)/);
  assert.match(health, /report\.interruptions\?\.judgment/);
  assert.match(health, /report\.recovery\.slice\(0, limit\)\.map/);
  assert.match(health, /report\.goodTimes\.slice\(0, limit\)\.map/);
  assert.match(health, /health-report-subjective/);
  assert.match(health, /hasUsefulReportText\(report\?\.oneExperiment\)/);
  assert.match(health, /health-report-experiment/);
  assert.doesNotMatch(styles, /\.health-deck-grid \{[\s\S]{0,220}min-height: min\(78vh/);
  assert.match(styles, /\.health-deck-grid \{[\s\S]{0,220}align-items: stretch/);
  assert.match(styles, /\.health-deck-card \{[\s\S]{0,220}height: 100%/);
  assert.match(styles, /\.health-deck-card \{[\s\S]{0,420}grid-template-rows: auto minmax\(0, 1fr\)/);
  assert.match(styles, /@media \(max-width: 900px\) \{[\s\S]{0,220}\.health-deck-card \{ min-height: 0; height: auto; grid-template-rows: auto auto; \}/);
  assert.match(styles, /@media \(min-width:901px\) and \(max-width:1100px\) \{[\s\S]{0,260}\.health-deck-grid \{\s*height: calc\(100dvh - 158px\)/);
  assert.match(styles, /\.health-cell-mind \.health-deck-card-body \{\s*display: grid;\s*grid-template-rows: minmax\(0, 66%\) minmax\(0, 34%\)/);
  assert.match(styles, /\.health-cell-life \.health-deck-card-body \{\s*display: grid;\s*grid-template-rows: minmax\(0, 55\.5%\) minmax\(0, 44\.5%\)/);
  assert.match(styles, /\.health-body-panel\.is-card \.coach-review-conclusion \{ display: none; \}/);
  assert.match(styles, /\.health-body-panel\.is-card \.muscle-legend \{ flex-wrap: nowrap; gap: 3px; \}/);
  assert.match(styles, /\.health-life-panel\.is-card \.life-gauges-block \.life-gauge-track \{ height: 42px; \}/);
  assert.match(styles, /\.health-mind-panel\.is-card \.mind-recovery-cell small \{ display: none; \}/);
  assert.match(main, /className="page-stack" data-reading-size=\{readingSize\}/);
  assert.match(styles, /data-reading-size="comfortable"[\s\S]{0,80}data-reading-size="large"[\s\S]{0,260}\.health-deck-grid \{\s*height: auto/);
  assert.match(styles, /\.health-mind-panel\.is-card \{\s*justify-content: flex-start/);
  assert.match(coach, /const conclusion = model\.conclusion/);
  assert.match(coach, /const items = model\.items/);
  assert.match(coach, /fullTexts: \[item\.text\]/);
  assert.match(coach, /coach-review-group-expanded/);
  assert.doesNotMatch(coach, /model\.(?:conclusion|items)\.slice/);
  assert.match(coach, /onOpenDetails/);
  assert.match(coach, /查看详情/);
  assert.match(coach, /\{!compact \? \(/);
  assert.match(styles, /\.health-deck-card-body > \.health-body-panel\.is-card \{\s*flex: 1 1 auto;\s*height: 100%/);
  assert.match(styles, /\.health-body-panel\.is-card > \.coach-review\.is-compact \{[\s\S]{0,160}flex: 1 1 auto/);
  assert.match(styles, /\.coach-review-groups \{[\s\S]{0,260}overflow-y: auto;[\s\S]{0,180}touch-action: pan-y/);
  assert.match(styles, /@media \(min-width: 901px\) \{[\s\S]{0,900}\.coach-review-group-expanded \{ display: inline; \}/);
  assert.doesNotMatch(mind, /<RecentWellbeing(?:\s|\/|>)/);
  assert.doesNotMatch(mind, /recentAssessment|weeklyMindSnapshots|NeedGroup|NeedBar|subjectiveSleep|appleSleepMinutes/);
  assert.match(mind, /近 14 日工作强度/);
  assert.match(mind, /推进与成果/);
  assert.match(mind, /打断与节奏/);
  assert.match(mind, /收工脱离/);
  assert.match(mind, /真放松/);
  assert.match(mind, /return "负荷 · 成果 · 恢复"/);
  assert.doesNotMatch(mind, /心理近况与量表参照|心理灵活性|倦怠|iWatch 记的睡眠/);
  assert.match(mind, /Math\.max\(0, Math\.min\(10, day\.workIntensity\)\)/);
  assert.match(mind, /clamped === 0 \? 3/);
  assert.match(mind, /variant === "full" \? 118 : 72/);
  assert.match(mind, /1 到 3 为青绿，4 到 7 为琥珀，8 以上转红/);
  assert.match(mind, /mind-energy-axis/);
  assert.match(mind, /mind-energy-value/);
  assert.match(styles, /\.mind-energy-coarse\.is-detail \.mind-energy-chart::before/);
  assert.match(styles, /\.mind-energy-bar\.is-e4,[\s\S]{0,180}\.mind-energy-bar\.is-e7 \{/);
  assert.match(styles, /\.mind-energy-bar\.is-e8 \{/);
  assert.match(styles, /\.mind-energy-bar\.is-e9,[\s\S]{0,80}\.mind-energy-bar\.is-e10 \{/);
  assert.match(mind, /recoveryPercents\?\.sampleDays/);
  assert.match(mind, /天有据/);
  assert.match(mind, /未知不会按 0 计算/);
  assert.doesNotMatch(life, /<RecentWellbeing(?:\s|\/|>)/);
  assert.match(life, /recentKnownGoodTime/);
  assert.match(life, /TwoQuestions surprise=\{currentSurprise\} refuel=\{currentRefuel\}/);
  assert.match(life, /最近时间明显偏向工作/);
  assert.doesNotMatch(life, /近期恢复：/);
  assert.doesNotMatch(life, /life-lean-tile[^>]*title=/);
  assert.match(life, /<Kicker>时间与精力投入<\/Kicker>/);
  assert.doesNotMatch(life, /相比上周|TrendLine/);
  assert.match(life, /<Kicker>好时光<\/Kicker>/);
  assert.match(life, /return "投入 · 好时光"/);
  assert.doesNotMatch(life, /TempBadge label="试运行"/);
  assert.doesNotMatch(life, /在推进的事项|工作观|人生观|选择四步|卡住时|奥德赛/);
  assert.doesNotMatch(life, /comparisonLabel|最近把时间和精力主要投向哪里/);
});
